typography_spectrum: 0.04386934614740312
content_rating:
  adult: false
color:
  brandColors:
    - '#ffffff'
    - '#040404'
    - '#adbac2'
    - '#8c4a0f'
    - '#6e6f6a'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.9192113978788257
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Moritz Krog
  email: moritzkrog@gmail.com
  url: 'https://plus.google.com/+Moritz.Krog'
name: Angry Mo
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Angry Mo
purpose: []
